### PR TITLE
Switch default core markup to output valid HTML5: styles & scripts declarations

### PR DESCRIPTION
**Pull request by audrasjb**
This PR fixes several HTML5 validation issues on script and styles HTML tags.

### CODE REVIEW

**Comment by kjellr** [comment]
Is this something that should just be added by default for all block themes?

**Comment by audrasjb** [comment]
Not sure. This is currently an opt-in feature for theme developers so I'd say it would be weird to maintain two cases, one for themes and another for block themes.

**Comment by kjellr** [comment]
For the record, a similar question came up a while back specifically regarding the comments block: https://github.com/WordPress/gutenberg/issues/30502.

**Comment by jffng** [comment]
Since https://github.com/WordPress/gutenberg/pull/35593 merged, shall we close this one?

**Comment by kjellr** [comment]
Yes, I think so. 👍

**Pull request closed without merging**
