### PR TITLE
added block image class

### PR DESCRIPTION
**Pull request by Riyadh1734**

### CODE REVIEW

**Comment by scruffian** [comment]
Thanks for the PR. Why are you adding the post title and content to the header template?

**Comment by Riyadh1734** [comment]
I think the block templates can have the same header included from a separate header.html template part.

**Comment by scruffian** [comment]
Yes that's right. I'd expect all block templates to use the same header.html template part, but I wouldn't expect the post content to be included in the header - I see the header more for things like the site title, logo and navigation.

**Comment by Riyadh1734** [comment]
what should I do any recommendations?

**Comment by scruffian** [comment]
What are you trying to achieve? I think most of the templates we need are already in place.

**Comment by Riyadh1734** [comment]
If no need for any change that's should be ok  & close it

**Comment by fabiankaegy** [comment]
I am going to close this PR for now based on the last comment here: https://github.com/WordPress/twentytwentytwo/pull/81#issuecomment-940137930

**Pull request closed without merging**
