### PR TITLE
header.php file added

### PR DESCRIPTION
**Pull request by Riyadh1734**

### CODE REVIEW

**Comment by Riyadh1734** [comment]
Displays all of the <head> section and everything up until main.

**Comment by Sandstromer** [comment]
This file is not required in a full site editing block theme.

**Comment by Riyadh1734** [comment]
ok

**Comment by Riyadh1734** [comment]
But I think header.html needed for a block theme.

**Comment by Riyadh1734** [comment]
header.html file already added...I missed sorry

**Comment by jffng** [comment]
Thanks everyone, going to close this PR as we're using a block template part for the header since this is a block theme.

**Pull request closed without merging**
