### PR TITLE
Changes to directory names

### PR DESCRIPTION
**Pull request by mburridge**
Changes the following directory names, as per issue #264 :

- `block-templates` ➡️ `templates`
- `block-template-parts` ➡️ `parts`

### CODE REVIEW

**Review by kjellr — APPROVED** [review]
Thanks! This works in my testing. 🙌

**Comment by kjellr** [comment]
After discussing with @jffng, we're going to hold off on merging for just a moment since this feature isn't merged into Beta 1 yet. Should be ready in a day or so!

**Comment by kafleg** [comment]
We are not going to change the name under Appearance?
See this screenshot: https://i.rankmath.com/ViRosf

**Comment by tinjure20** [comment]
I was also wondering how about use in templates markup (example: [here](https://github.com/WordPress/twentytwentytwo/blob/trunk/block-templates/index.html#L1))?

**Comment by carolinan** [comment]
> I was also wondering how about use in templates markup (example: [here](https://github.com/WordPress/twentytwentytwo/blob/trunk/block-templates/index.html#L1))?

The markup uses the source and slug for the block, wp:template-part, and the name of the template part block has not been changed, so we don't need to change anything there.

**Comment by carolinan** [comment]
> We are not going to change the name under Appearance? See this screenshot: https://i.rankmath.com/ViRosf

I don't think so, there were discussions a few months ago, but not recently.

**Comment by kjellr** [comment]
The [release bundled here](https://github.com/WordPress/twentytwentytwo/releases/tag/v0.4.0) has been committed to core for Beta 1, so I think we're good to merge this. 

I think this'll mean folks need to test this GitHub edition of the theme against Gutenberg `trunk` until 12.1 comes out, but that should be fine since folks can still test the version bundled with Beta 1.  

Thanks, everyone!

**Pull request merged**
