### PR TITLE
Hide "Comments Closed" message

### PR DESCRIPTION
**Pull request by jffng**
**Description**

This PR is an alternative to #127 per some discussion in this trac ticket https://core.trac.wordpress.org/ticket/54283 (thanks @audrasjb for opening). It depends on https://github.com/WordPress/gutenberg/pull/35743

**Testing Instructions** 

1. Check out the above Gutenberg PR and build it.
2. Go to a post or page whose comments are disallowed
3. Verify the message is hidden

### CODE REVIEW

**Comment by kjellr** [comment]
Assuming this attribute is needed, this could probably be worked into #127 (or vice versa? That PR now includes some spacing stuff that will be needed either way).

**Comment by jffng** [comment]
> Assuming this attribute is needed, this could probably be worked into #127 (or vice versa? That PR now includes some spacing stuff that will be needed either way).

Yes, can work this into #127. But your question made me think, do we even need the attribute?

**Comment by kjellr** [comment]
Yeah, I don't think we do. That message should just be hidden when there are no comments + comments are closed.

**Comment by jffng** [comment]
I updated the Gutenberg PR to do that, going to close this one in favor of #127.

**Pull request closed without merging**
